<a href="https://colab.research.google.com/github/v1umahmo/HonoursProject/blob/main/HonoursCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import Necessary Libraries

In [ ]:
#For data processing
import pandas as pd
#For linear algebra
import numpy as np
#Regular expression library
import re
#Natural Language Toolkit
import nltk
import seaborn as sns
import warnings
import matplotlib.pyplot as plt


### Import the Training and Testing Data

In [ ]:
train = pd.read_csv("/content/train.csv") # Import training data from file path
test = pd.read_csv("/content/test.csv") # Import test data from file path

### Look At The Training Data

In [ ]:
train.info() # Print training data info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31962 entries, 0 to 31961
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      31962 non-null  int64 
 1   label   31962 non-null  int64 
 2   tweet   31962 non-null  object
dtypes: int64(2), object(1)
memory usage: 749.2+ KB


In [ ]:
train.head(10) # Print the first ten tweets from the training data

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation
5   6      0  [2/2] huge fan fare and big talking before the...
6   7      0   @user camping tomorrow @user @user @user @use...
7   8      0  the next school year is the year for exams.ðŸ˜...
8   9      0  we won!!! love the land!!! #allin #cavs #champ...
9  10      0   @user @user welcome here !  i'm   it's so #gr...

In [ ]:
train.tail(10) # Print the last ten tweets from the training data

id  label                                              tweet
31952  31953      0                @user you went too far with @user  
31953  31954      0  good morning #instagram #shower #water #berlin...
31954  31955      0  #holiday   bull up: you will dominate your bul...
31955  31956      0  less than 2 weeks ðŸ˜
🙏🏼🍹😎🎵 @us...
31956  31957      0  off fishing tomorrow @user carnt wait first ti...
31957  31958      0  ate @user isz that youuu?😍😍😍😍😍ð...
31958  31959      0    to see nina turner on the airwaves trying to...
31959  31960      0  listening to sad songs on a monday morning otw...
31960  31961      1  @user #sikh #temple vandalised in in #calgary,...
31961  31962      0                   thank you @user for you follow

### Clean The Training Data

In [ ]:
# For loop to go through each tweet for the data cleaning
def remove_pattern(input_txt, pattern):
  r = re.findall(pattern, input_txt)
  for i in r:
    input_txt = re.sub(i, ' ', input_txt)
  return input_txt

In [ ]:
# Get Rid of the user handles
train['cleaned_tweets'] = np.vectorize(remove_pattern)(train['tweet'], "@[\w]*")

In [ ]:
train.head(10) # Print the first ten tweets from the training data with their twitter handles removed

id  ...                                     cleaned_tweets
0   1  ...     when a father is dysfunctional and is so se...
1   2  ...      thanks for #lyft credit i can't use cause ...
2   3  ...                                bihday your majesty
3   4  ...  #model   i love u take with u all the time in ...
4   5  ...             factsguide: society now    #motivation
5   6  ...  [2/2] huge fan fare and big talking before the...
6   7  ...            camping tomorrow               danny…
7   8  ...  the next school year is the year for exams.ðŸ˜...
8   9  ...  we won!!! love the land!!! #allin #cavs #champ...
9  10  ...              welcome here !  i'm   it's so #gr8 ! 

[10 rows x 4 columns]

In [ ]:
# Make tweets lower case
train['cleaned_tweets'] = train['cleaned_tweets'].apply(lambda x: x.lower())

In [ ]:
train.head(10) # Print the first ten tweets from the training data with the tweets lower case

id  ...                                     cleaned_tweets
0   1  ...     when a father is dysfunctional and is so se...
1   2  ...      thanks for #lyft credit i can't use cause ...
2   3  ...                                bihday your majesty
3   4  ...  #model   i love u take with u all the time in ...
4   5  ...             factsguide: society now    #motivation
5   6  ...  [2/2] huge fan fare and big talking before the...
6   7  ...            camping tomorrow               danny…
7   8  ...  the next school year is the year for exams.ðŸ˜...
8   9  ...  we won!!! love the land!!! #allin #cavs #champ...
9  10  ...              welcome here !  i'm   it's so #gr8 ! 

[10 rows x 4 columns]

In [ ]:
# Remove hashtags and punctuation
train['cleaned_tweets'] = train['cleaned_tweets'].apply(lambda x: re.sub(r'[^\w\s]',' ',x))

In [ ]:
train.head(10)

id  ...                                     cleaned_tweets
0   1  ...     when a father is dysfunctional and is so se...
1   2  ...      thanks for  lyft credit i can t use cause ...
2   3  ...                                bihday your majesty
3   4  ...   model   i love u take with u all the time in ...
4   5  ...             factsguide  society now     motivation
5   6  ...   2 2  huge fan fare and big talking before the...
6   7  ...            camping tomorrow               dannyâ  
7   8  ...  the next school year is the year for exams ð  ...
8   9  ...  we won    love the land     allin  cavs  champ...
9  10  ...              welcome here    i m   it s so  gr8   

[10 rows x 4 columns]

In [ ]:
# Remove numbers and special characters etc.
train['cleaned_tweets'] = train['cleaned_tweets'].apply(lambda x: re.sub(r'[^a-zA-z]',' ',x))

In [ ]:
train.head(10)

id  ...                                     cleaned_tweets
0   1  ...     when a father is dysfunctional and is so se...
1   2  ...      thanks for  lyft credit i can t use cause ...
2   3  ...                                bihday your majesty
3   4  ...   model   i love u take with u all the time in ...
4   5  ...             factsguide  society now     motivation
5   6  ...        huge fan fare and big talking before the...
6   7  ...            camping tomorrow               danny   
7   8  ...  the next school year is the year for exams    ...
8   9  ...  we won    love the land     allin  cavs  champ...
9  10  ...              welcome here    i m   it s so  gr    

[10 rows x 4 columns]

In [ ]:
# Import libraries for tokenization and stopwords
from nltk.tokenize import word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
# Create tokenization for the cleaned tweets
train['tokenized_tweets'] = train['cleaned_tweets'].apply(lambda x: word_tokenize(x))

In [ ]:
train.head(10)

id  ...                                   tokenized_tweets
0   1  ...  [when, a, father, is, dysfunctional, and, is, ...
1   2  ...  [thanks, for, lyft, credit, i, can, t, use, ca...
2   3  ...                            [bihday, your, majesty]
3   4  ...  [model, i, love, u, take, with, u, all, the, t...
4   5  ...             [factsguide, society, now, motivation]
5   6  ...  [huge, fan, fare, and, big, talking, before, t...
6   7  ...                         [camping, tomorrow, danny]
7   8  ...  [the, next, school, year, is, the, year, for, ...
8   9  ...  [we, won, love, the, land, allin, cavs, champi...
9  10  ...               [welcome, here, i, m, it, s, so, gr]

[10 rows x 5 columns]

In [ ]:
# Use this to remove words such as if, but, can etc. (Words that have no value)
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
stop_words

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [ ]:
# Apply stopwords to the tokenized tweets
train['tokenized_tweets_filtered'] = train['tokenized_tweets'].apply(lambda x: [word for word in x if not word in stop_words])

In [ ]:
train.head(10)

id  ...                          tokenized_tweets_filtered
0   1  ...  [father, dysfunctional, selfish, drags, kids, ...
1   2  ...  [thanks, lyft, credit, use, cause, offer, whee...
2   3  ...                                  [bihday, majesty]
3   4  ...                [model, love, u, take, u, time, ur]
4   5  ...                  [factsguide, society, motivation]
5   6  ...  [huge, fan, fare, big, talking, leave, chaos, ...
6   7  ...                         [camping, tomorrow, danny]
7   8  ...  [next, school, year, year, exams, think, schoo...
8   9  ...  [love, land, allin, cavs, champions, cleveland...
9  10  ...                                      [welcome, gr]

[10 rows x 6 columns]

In [ ]:
#Import library for stemming
from nltk.stem import PorterStemmer
stemming = PorterStemmer()

In [ ]:
#Stem the tweets and create another colim for tweets that are stemmed
train['stemmed_tweets'] = train['tokenized_tweets_filtered'].apply(lambda x: ' '.join([stemming.stem(i) for i in x]))

In [ ]:
train.head(10)

id  ...                                     stemmed_tweets
0   1  ...      father dysfunct selfish drag kid dysfunct run
1   2  ...  thank lyft credit use caus offer wheelchair va...
2   3  ...                                     bihday majesti
3   4  ...                        model love u take u time ur
4   5  ...                            factsguid societi motiv
5   6  ...  huge fan fare big talk leav chao pay disput ge...
6   7  ...                                camp tomorrow danni
7   8  ...  next school year year exam think school exam h...
8   9  ...  love land allin cav champion cleveland clevela...
9  10  ...                                          welcom gr

[10 rows x 7 columns]

In [ ]:
#Import library for lemmatizing
from nltk.stem.wordnet import WordNetLemmatizer
nltk.download('wordnet')
lemmatizing = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
# Lemmatize the tweets and create another column for tweets that are lemmatized
train['lemmatized_tweets'] = train['tokenized_tweets_filtered'].apply(lambda x: ' ' .join([lemmatizing.lemmatize(i) for i in x]))

In [ ]:
train.head(10)

id  ...                                  lemmatized_tweets
0   1  ...  father dysfunctional selfish drag kid dysfunct...
1   2  ...  thanks lyft credit use cause offer wheelchair ...
2   3  ...                                     bihday majesty
3   4  ...                        model love u take u time ur
4   5  ...                      factsguide society motivation
5   6  ...  huge fan fare big talking leave chaos pay disp...
6   7  ...                             camping tomorrow danny
7   8  ...  next school year year exam think school exam h...
8   9  ...  love land allin cavs champion cleveland clevel...
9  10  ...                                         welcome gr

[10 rows x 8 columns]

### Apply Feature Extraction

Consider adding CountVectorizer, this might come in handy when comparing results, and evaluation

In [ ]:
# CountVectorizer converts a collection of text documents to a matrix of token counts.
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
# TfidfVectorizer converts a collection of raw documents to a matrix of TF-IDF features. Combination of CountVectorizer and TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf = TfidfVectorizer(max_df=0.90, min_df=2, max_features=1000, stop_words='english')
tf_idf 

TfidfVectorizer(max_df=0.9, max_features=1000, min_df=2, stop_words='english')

In [ ]:
traintfidf_stem = tf_idf.fit_transform(train['stemmed_tweets'])
traintfidf_stem.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
traintfidf_lemm = tf_idf.fit_transform(train['lemmatized_tweets'])
traintfidf_lemm.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### Clean The Test Data

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17197 entries, 0 to 17196
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      17197 non-null  int64 
 1   tweet   17197 non-null  object
dtypes: int64(1), object(1)
memory usage: 268.8+ KB


In [ ]:
test.head(10)

id                                              tweet
0  31963  #studiolife #aislife #requires #passion #dedic...
1  31964   @user #white #supremacists want everyone to s...
2  31965  safe ways to heal your #acne!!    #altwaystohe...
3  31966  is the hp and the cursed child book up for res...
4  31967    3rd #bihday to my amazing, hilarious #nephew...
5  31968                        choose to be   :) #momtips 
6  31969  something inside me dies 💦💿✨  eyes nes...
7  31970  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...
8  31971   @user @user @user i will never understand why...
9  31972  #delicious   #food #lovelife #capetown mannaep...

In [ ]:
test.tail(10)

id                                              tweet
17187  49150  loving life🇺🇸☀️🏊  #createyourfutu...
17188  49151  black professor demonizes, proposes nazi style...
17189  49152  learn how to think positive.  #positive   #ins...
17190  49153  we love the pretty, happy and fresh you! #teen...
17191  49154  2_damn_tuff-ruff_muff__techno_city-(ng005)-web...
17192  49155  thought factory: left-right polarisation! #tru...
17193  49156  feeling like a mermaid 😘 #hairflip #neverre...
17194  49157  #hillary #campaigned today in #ohio((omg)) &am...
17195  49158  happy, at work conference: right mindset leads...
17196  49159  my   song "so glad" free download!  #shoegaze ...

In [ ]:
# Get Rid of the user handles
test['cleaned_tweets'] = np.vectorize(remove_pattern)(test['tweet'], "@[\w]*")

In [ ]:
test.head(10)

id  ...                                     cleaned_tweets
0  31963  ...  #studiolife #aislife #requires #passion #dedic...
1  31964  ...     #white #supremacists want everyone to see t...
2  31965  ...  safe ways to heal your #acne!!    #altwaystohe...
3  31966  ...  is the hp and the cursed child book up for res...
4  31967  ...    3rd #bihday to my amazing, hilarious #nephew...
5  31968  ...                        choose to be   :) #momtips 
6  31969  ...  something inside me dies 💦💿✨  eyes nes...
7  31970  ...  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...
8  31971  ...         i will never understand why my dad left...
9  31972  ...  #delicious   #food #lovelife #capetown mannaep...

[10 rows x 3 columns]

In [ ]:
# Make tweets lower case
test['cleaned_tweets'] = test['cleaned_tweets'].apply(lambda x: x.lower())

In [ ]:
test.head(10)

id  ...                                     cleaned_tweets
0  31963  ...  #studiolife #aislife #requires #passion #dedic...
1  31964  ...     #white #supremacists want everyone to see t...
2  31965  ...  safe ways to heal your #acne!!    #altwaystohe...
3  31966  ...  is the hp and the cursed child book up for res...
4  31967  ...    3rd #bihday to my amazing, hilarious #nephew...
5  31968  ...                        choose to be   :) #momtips 
6  31969  ...  something inside me dies 💦💿✨  eyes nes...
7  31970  ...  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...
8  31971  ...         i will never understand why my dad left...
9  31972  ...  #delicious   #food #lovelife #capetown mannaep...

[10 rows x 3 columns]

In [ ]:
test['cleaned_tweets'] = test['cleaned_tweets'].apply(lambda x: re.sub(r'[^\w\s]',' ',x))

In [ ]:
test.head(10)

id  ...                                     cleaned_tweets
0  31963  ...   studiolife  aislife  requires  passion  dedic...
1  31964  ...      white  supremacists want everyone to see t...
2  31965  ...  safe ways to heal your  acne       altwaystohe...
3  31966  ...  is the hp and the cursed child book up for res...
4  31967  ...    3rd  bihday to my amazing  hilarious  nephew...
5  31968  ...                        choose to be       momtips 
6  31969  ...  something inside me dies ð   ð   â    eyes nes...
7  31970  ...   finished tattoo inked ink loveitâ  ï    â  ï ...
8  31971  ...         i will never understand why my dad left...
9  31972  ...   delicious    food  lovelife  capetown mannaep...

[10 rows x 3 columns]

In [ ]:
test['cleaned_tweets'] = test['cleaned_tweets'].apply(lambda x: re.sub(r'[^a-zA-z]',' ',x))

In [ ]:
test.head(10)

id  ...                                     cleaned_tweets
0  31963  ...   studiolife  aislife  requires  passion  dedic...
1  31964  ...      white  supremacists want everyone to see t...
2  31965  ...  safe ways to heal your  acne       altwaystohe...
3  31966  ...  is the hp and the cursed child book up for res...
4  31967  ...     rd  bihday to my amazing  hilarious  nephew...
5  31968  ...                        choose to be       momtips 
6  31969  ...  something inside me dies              eyes nes...
7  31970  ...   finished tattoo inked ink loveit             ...
8  31971  ...         i will never understand why my dad left...
9  31972  ...   delicious    food  lovelife  capetown mannaep...

[10 rows x 3 columns]

In [ ]:
# Import libraries for tokenization and stopwords
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [ ]:
# Create tokenization for the cleaned tweets
test['tokenized_tweets'] = test['cleaned_tweets'].apply (lambda x: word_tokenize(x))

In [ ]:
test.head(10)

id  ...                                   tokenized_tweets
0  31963  ...  [studiolife, aislife, requires, passion, dedic...
1  31964  ...  [white, supremacists, want, everyone, to, see,...
2  31965  ...  [safe, ways, to, heal, your, acne, altwaystohe...
3  31966  ...  [is, the, hp, and, the, cursed, child, book, u...
4  31967  ...  [rd, bihday, to, my, amazing, hilarious, nephe...
5  31968  ...                          [choose, to, be, momtips]
6  31969  ...  [something, inside, me, dies, eyes, ness, smok...
7  31970  ...  [finished, tattoo, inked, ink, loveit, thanks,...
8  31971  ...  [i, will, never, understand, why, my, dad, lef...
9  31972  ...  [delicious, food, lovelife, capetown, mannaepi...

[10 rows x 4 columns]

In [ ]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [ ]:
test['tokenized_tweets_filtered'] = test['tokenized_tweets'].apply(lambda x: [word for word in x if not word in stop_words])

In [ ]:
test.head(10)

id  ...                          tokenized_tweets_filtered
0  31963  ...  [studiolife, aislife, requires, passion, dedic...
1  31964  ...  [white, supremacists, want, everyone, see, new...
2  31965  ...  [safe, ways, heal, acne, altwaystoheal, health...
3  31966  ...  [hp, cursed, child, book, reservations, alread...
4  31967  ...  [rd, bihday, amazing, hilarious, nephew, eli, ...
5  31968  ...                                  [choose, momtips]
6  31969  ...  [something, inside, dies, eyes, ness, smokeyey...
7  31970  ...  [finished, tattoo, inked, ink, loveit, thanks,...
8  31971  ...  [never, understand, dad, left, young, deep, in...
9  31972  ...  [delicious, food, lovelife, capetown, mannaepi...

[10 rows x 5 columns]

In [ ]:
#Import library for stemming
from nltk.stem import PorterStemmer
stemming = PorterStemmer()

In [ ]:
#Stem the tweets and create another colim for tweets that are stemmed
test['stemmed_tweets'] = test['tokenized_tweets_filtered'].apply(lambda x: ' '.join([stemming.stem(i) for i in x]))

In [ ]:
test.head(10)

id  ...                                     stemmed_tweets
0  31963  ...  studiolif aislif requir passion dedic willpow ...
1  31964  ...   white supremacist want everyon see new bird movi
2  31965  ...          safe way heal acn altwaystoh healthi heal
3  31966  ...  hp curs child book reserv alreadi ye harrypott...
4  31967  ...  rd bihday amaz hilari nephew eli ahmir uncl da...
5  31968  ...                                       choos momtip
6  31969  ...  someth insid die eye ness smokeyey tire lone s...
7  31970  ...           finish tattoo ink ink loveit thank aleee
8  31971  ...     never understand dad left young deep inthefeel
9  31972  ...    delici food lovelif capetown mannaepicur restur

[10 rows x 6 columns]

In [ ]:
#Import library for lemmatizing
from nltk.stem.wordnet import WordNetLemmatizer
lemmatizing = WordNetLemmatizer()

In [ ]:
test['lemmatized_tweets'] = test['tokenized_tweets_filtered'].apply(lambda x: ' ' .join([lemmatizing.lemmatize(i) for i in x]))

In [ ]:
test.head(10)

id  ...                                  lemmatized_tweets
0  31963  ...  studiolife aislife requires passion dedication...
1  31964  ...  white supremacist want everyone see new bird m...
2  31965  ...   safe way heal acne altwaystoheal healthy healing
3  31966  ...  hp cursed child book reservation already yes h...
4  31967  ...  rd bihday amazing hilarious nephew eli ahmir u...
5  31968  ...                                     choose momtips
6  31969  ...  something inside dy eye ness smokeyeyes tired ...
7  31970  ...     finished tattoo inked ink loveit thanks aleeee
8  31971  ...    never understand dad left young deep inthefeels
9  31972  ...  delicious food lovelife capetown mannaepicure ...

[10 rows x 7 columns]

### Apply Feature Extraction

In [ ]:
# Import library
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf = TfidfVectorizer(max_df=0.90, min_df=2, max_features=1000, stop_words='english')
tf_idf 

TfidfVectorizer(max_df=0.9, max_features=1000, min_df=2, stop_words='english')

In [ ]:
testtfidf_stem = tf_idf.fit_transform(test['stemmed_tweets'])
testtfidf_stem.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
testtfidf_lemm = tf_idf.fit_transform(train['lemmatized_tweets'])
testtfidf_lemm.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### Machine Learning

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

### Train & Test Split With Lemmatized Data

In [ ]:
x = traintfidf_lemm
y = train['label']

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size = 0.3,random_state = 42)

### Applying SVM using Lemmatized Data

In [ ]:
svc = SVC()
svc.fit(xtrain,ytrain)
predict_svc = svc.predict(xtest)

In [ ]:
print(accuracy_score(predict_svc,ytest))
print(confusion_matrix(predict_svc,ytest))

0.9479612055480238
[[8847  441]
 [  58  243]]


In [ ]:
print(classification_report(predict_svc, ytest))

              precision    recall  f1-score   support

           0       0.99      0.95      0.97      9288
           1       0.36      0.81      0.49       301

    accuracy                           0.95      9589
   macro avg       0.67      0.88      0.73      9589
weighted avg       0.97      0.95      0.96      9589



### Applying Naïve Bayes using Lemmatized Data

In [ ]:
na_bay = GaussianNB()
na_bay.fit(xtrain.toarray(),ytrain)
predict_na_bay = na_bay.predict(xtest.toarray())

In [ ]:
print(accuracy_score(predict_na_bay,ytest))
print(confusion_matrix(predict_na_bay,ytest))

0.5803524872249453
[[4940   59]
 [3965  625]]


In [ ]:
print(classification_report(predict_na_bay, ytest))

              precision    recall  f1-score   support

           0       0.99      0.95      0.97      9288
           1       0.36      0.81      0.49       301

    accuracy                           0.95      9589
   macro avg       0.67      0.88      0.73      9589
weighted avg       0.97      0.95      0.96      9589



### Applying Logistic Regression using Lemmatized Data

In [ ]:
log_reg = LogisticRegression()
log_reg.fit(xtrain,ytrain)
predict_log_reg = log_reg.predict(xtest)

In [ ]:
print(accuracy_score(predict_log_reg, ytest))
print(confusion_matrix(predict_log_reg, ytest))

0.9469183439357597
[[8854  458]
 [  51  226]]


In [ ]:
print(classification_report(predict_log_reg, ytest))

              precision    recall  f1-score   support

           0       0.99      0.95      0.97      9288
           1       0.36      0.81      0.49       301

    accuracy                           0.95      9589
   macro avg       0.67      0.88      0.73      9589
weighted avg       0.97      0.95      0.96      9589



### Train & Test Split with Stemmed Data

In [ ]:
x2 = traintfidf_stem
y2 = train['label']

In [ ]:
x2train,x2test,y2train,y2test=train_test_split(x2,y2,test_size = 0.3,random_state = 42)

### Applying SVM using Stemmed Data

In [ ]:
svc2 = SVC()
svc2.fit(x2train,y2train)
predict_svc2 = svc.predict(x2test)

In [ ]:
print(accuracy_score(predict_svc2,y2test))
print(confusion_matrix(predict_svc2,y2test))

0.9183439357597247
[[8801  679]
 [ 104    5]]


In [ ]:
print(classification_report(predict_svc2, y2test))

              precision    recall  f1-score   support

           0       0.99      0.93      0.96      9480
           1       0.01      0.05      0.01       109

    accuracy                           0.92      9589
   macro avg       0.50      0.49      0.49      9589
weighted avg       0.98      0.92      0.95      9589



### Applying Naïve Bayes using Stemmed Data

In [ ]:
na_bay2 = GaussianNB()
na_bay2.fit(x2train.toarray(),y2train)
predict_na_bay2 = na_bay2.predict(x2test.toarray())

In [ ]:
print(accuracy_score(predict_na_bay2,y2test))
print(confusion_matrix(predict_na_bay2,y2test))

0.5574095317551361
[[4733   72]
 [4172  612]]


In [ ]:
print(classification_report(predict_na_bay2, y2test))

              precision    recall  f1-score   support

           0       0.53      0.99      0.69      4805
           1       0.89      0.13      0.22      4784

    accuracy                           0.56      9589
   macro avg       0.71      0.56      0.46      9589
weighted avg       0.71      0.56      0.46      9589



### Applying Logistic Regression to Stemmed Data



In [ ]:
log_reg2 = LogisticRegression()
log_reg2.fit(x2train,y2train)
predict_log_reg2 = log_reg.predict(x2test)

In [ ]:
print(accuracy_score(predict_log_reg2, y2test))
print(confusion_matrix(predict_log_reg2, y2test))

0.9215768067577432
[[8835  682]
 [  70    2]]


In [ ]:
print(classification_report(predict_log_reg2, y2test))

              precision    recall  f1-score   support

           0       0.99      0.93      0.96      9517
           1       0.00      0.03      0.01        72

    accuracy                           0.92      9589
   macro avg       0.50      0.48      0.48      9589
weighted avg       0.98      0.92      0.95      9589

